Repository ubiquitypress/hyku, pull requests merged in 2019-06, with the labels that each got.

#384 Add UI option to allow the user to edit the email address and added a…
  app/controllers/concerns/ubiquity/contact_form_controller_override.rb
  app/controllers/ubiquity/account_settings_controller.rb
  app/helpers/ubiquity/account_settings_helper.rb
  app/mailers/hyrax/contact_mailer.rb
  app/models/concerns/ubiquity/account_self_join_association.rb
  app/views/hyrax/dashboard/_sidebar.html.erb
  app/views/shared/ubiquity/contact/_new.html.erb
  app/views/ubiquity/account_settings/edit.html.erb
  app/views/ubiquity/account_settings/index.html.erb
  config/locales/en.yml
  config/routes.rb
  spec/controllers/ubiquity/account_settings_controller_spec.rb
  spec/helpers/ubiquity/account_settings_helper_spec.rb
  spec/views/ubiquity/account_settings/index.html.erb_spec.rb
Labels: approved

#383 Collection view changes
  app/assets/images/details_close.png
  app/assets/images/details_open.png
  app/assets/javascripts/application.js
  app/assets/javascripts/ubiquity/datatable-settings.js
  app/assets/stylesheets/ubiquity.scss
  app/assets/stylesheets/ubiquity/external_services.scss
  app/forms/ubiquity/collection_form_behaviour.rb
  app/helpers/ubiquity/collection_list_helper.rb
  app/models/concerns/ubiquity/collection_list_per_page.rb
  app/views/hyrax/collections/_collection_title.html.erb
  app/views/hyrax/collections/_search_form.html.erb
  app/views/hyrax/collections/_sort_and_per_page.html.erb
  app/views/hyrax/dashboard/collections/_sort_and_per_page.html.erb
  app/views/shared/ubiquity/collections/_collection_title.html.erb
  app/views/shared/ubiquity/collections/_show_descriptions.html.erb
  app/views/shared/ubiquity/collections/_show_document_list.html.erb
  app/views/shared/ubiquity/collections/_show_document_list_row.html.erb
  config/application.rb
Labels: approved, ready_to_merge

#385 change the check for deleting the work pop up message
  app/assets/javascripts/ubiquity/external_services_modal.js
  app/helpers/ubiquity/work_show_actions_helper.rb
Labels: approved, ready_to_merge

#381 reindex a work in shared-search if a file is added or if the collection is updated or deleted "
  app/models/concerns/ubiquity/update_shared_index.rb
  app/services/ubiquity/shared_index_solr_service_wrapper.rb
  app/views/shared/ubiquity/catalog/_index_list_default.html.erb
Labels: approved, ready_to_merge

#386 Setting the default value for the admin set
  app/assets/javascripts/ubiquity/custom_required_fields.js
  app/views/hyrax/base/_form_relationships.html.erb
  app/views/shared/ubiquity/works/_form_relationships.html.erb
Labels: approved, ready_to_merge

#387 changed the query to pluck the cname
  app/services/ubiquity/expiry_service.rb
Labels: approved, ready_to_merge

#388 refactor alternative title to follow Hyrax samvera pattern
  app/assets/javascripts/ubiquity/title_check.js
  app/controllers/available_ubiquity_titles_controller.rb
  app/controllers/catalog_controller.rb
  app/forms/hyrax/article_form.rb
  app/forms/hyrax/book_contribution_form.rb
  app/forms/hyrax/book_form.rb
  app/forms/hyrax/conference_item_form.rb
  app/forms/hyrax/dataset_form.rb
  app/forms/hyrax/generic_work_form.rb
  app/forms/hyrax/image_form.rb
  app/forms/hyrax/report_form.rb
  app/models/concerns/ubiquity/basic_metadata_decorator.rb
  app/models/solr_document.rb
  app/presenters/hyku/manifest_enabled_work_show_presenter.rb
  app/services/ubiquity/title_checker.rb
  app/views/hyrax/base/_attribute_rows.html.erb
  app/views/records/edit_fields/_alt_title.html.erb
  app/views/records/edit_fields/_alternative_title.html.erb
  config/locales/article.en.yml
Labels: approved

#390 Fixed the issue in the Alternative Journal Title display form
  app/models/solr_document.rb
Labels: approved, ready_to_merge

#391 Renamed the generic work name in the pop up modal
  config/locales/generic_work.en.yml
Labels: approved, ready_to_merge

#393 Added volumne and issue fields for the cross ref url
  app/assets/javascripts/ubiquity/datacite.js
  app/services/ubiquity/crossref_response.rb
  app/views/records/edit_fields/_issue.html.erb
  app/views/records/edit_fields/_pagination.html.erb
Labels: approved, ready_to_merge

#392 Added expiry service model and the rake task to populate the records …
  app/jobs/ubiquity_expiry_job.rb
  app/jobs/ubiquity_work_expiry_job.rb
  app/models/concerns/ubiquity/all_models_virtual_fields.rb
  app/models/file_set.rb
  app/models/work_expiry_service.rb
  app/services/ubiquity/expiry_service.rb
  config/initializers/apartment.rb
  db/migrate/20190604123004_create_work_expiry_services.rb
  db/schema.rb
  lib/tasks/create_expiry_service_records.rake
  spec/models/work_expiry_service_spec.rb
Labels: approved, ready_to_merge

#396 escaped the invalid url characters to url friendly
  app/models/concerns/ubiquity/all_models_virtual_fields.rb
Labels: approved, ready_to_merge

#395 Cross ref url issue
  app/services/ubiquity/crossref_response.rb
Labels: approved, ready_to_merge

#398 Fixed squishing for the url class values
  app/models/concerns/ubiquity/all_models_virtual_fields.rb
Labels: approved, ready_to_merge

#397 Collection view new changes
  app/assets/javascripts/ubiquity/datatable-settings.js
  app/assets/stylesheets/ubiquity.scss
  app/views/shared/ubiquity/collections/_show_document_list.html.erb
  app/views/shared/ubiquity/collections/_show_document_list_row.html.erb
Labels: approved, ready_to_merge

#399 Removed the status column reference from the new model
  app/models/concerns/ubiquity/all_models_virtual_fields.rb
  app/models/file_set.rb
  app/services/ubiquity/expiry_service.rb
Labels: approved, ready_to_merge

#401 Added referencing the embargo_Release_date and lease_expiration_date
  app/jobs/ubiquity_work_expiry_job.rb
  app/models/file_set.rb
  lib/tasks/create_expiry_service_records.rake
Labels: approved, ready_to_merge

#404 Fixed the collection table issue in the UI
  app/helpers/multiple_metadata_fields_helper.rb
  app/helpers/ubiquity/collection_list_helper.rb
  app/services/ubiquity/parse_json.rb
  app/views/shared/ubiquity/collections/_show_document_list_row.html.erb
Labels: approved, ready_to_merge

#402 Added try in the release date check for embargo and lease
  app/jobs/ubiquity_work_expiry_job.rb
  lib/tasks/create_expiry_service_records.rake
Labels: approved, ready_to_merge

#406 fixed alternative-journal-title
  app/forms/hyrax/generic_work_form.rb
Labels: ready_to_merge

#400 Fixed the thumbnail issue in the file sets and the work listing
  app/helpers/application_helper.rb
  app/helpers/ubiquity/file_display_helpers.rb
  app/presenters/concerns/displays_image.rb
  app/views/shared/ubiquity/_thumbnail_featured.html.erb
  app/views/shared/ubiquity/_thumbnail_icons.html.erb
  app/views/shared/ubiquity/_thumbnail_icons_with_restrictions.html.erb
  app/views/shared/ubiquity/search_display/_search_thumbnail.html.erb
Labels: approved, ready_to_merge

#403 Export records to CSV after remapping the keys and then reordering based on the order given by Bl
  app/models/concerns/ubiquity/csv_export_util.rb
  app/services/ubiquity/csv_data.rb
  app/services/ubiquity/csv_data_remap.rb
  app/services/ubiquity/csv_generator.rb
  app/views/admin/exports/index.html.erb
Labels: approved, ready_to_merge

#405 Rif format feature
  app/controllers/concerns/ubiquity/citations_export_concern.rb
  app/controllers/ubiquity/citation_exports_controller.rb
  app/services/ubiquity/parse_json.rb
  app/views/hyrax/base/_citations.html.erb
  app/views/shared/ubiquity/citations/_export_to_rif.html.erb
  config/routes.rb
Labels: approved, ready_to_merge

#407 allow json importer to update records based on keys in imported csv
  app/services/ubiquity/json_importer.rb
  app/services/ubiquity/queue_import.rb
Labels: approved, ready_to_merge

#408 Changed the typo in submitting the contact form
  app/views/shared/ubiquity/contact/_new.html.erb
Labels: approved, ready_to_merge

#409 Filters
  app/controllers/catalog_controller.rb
  app/models/article.rb
  app/models/book.rb
  app/models/book_contribution.rb
  app/models/concerns/ubiquity/basic_metadata_decorator.rb
  app/models/concerns/ubiquity/file_utility_methods.rb
  app/models/concerns/ubiquity/multiple_modules.rb
  app/models/concerns/ubiquity/update_shared_index.rb
  app/models/concerns/ubiquity/work_doi_lifecycle.rb
  app/models/conference_item.rb
  app/models/dataset.rb
  app/models/exhibition.rb
  app/models/file_set.rb
  app/models/generic_work.rb
  app/models/image.rb
  app/models/report.rb
  app/models/thesis_or_dissertation.rb
  app/models/time_based_media.rb
  lib/tasks/ubiquity_index_file_availability_facet.rake
  spec/jobs/ubiquity_file_facet_doi_job_spec.rb
  supervisord.log
Labels: approved, ready_to_merge

#411 Cross ref issn type update
  app/helpers/multiple_metadata_fields_helper.rb
  app/models/concerns/ubiquity/all_models_virtual_fields.rb
  app/services/ubiquity/crossref_response.rb
Labels: approved, ready_to_merge

#414 Fixed the issue in the shared search using the old method to render t…
  app/views/shared/ubiquity/search_display/_search_thumbnail.html.erb
Labels: approved, ready_to_merge

#415 ResolvedTab reports section
  app/controllers/ubiquity/account_settings_controller.rb
  app/models/concerns/ubiquity/account_self_join_association.rb
  app/views/hyrax/admin/stats/_email_reports.html.erb
  app/views/hyrax/admin/stats/show.html.erb
  app/views/ubiquity/account_settings/edit.html.erb
  app/views/ubiquity/account_settings/index.html.erb
Labels: approved, ready_to_merge

#416 Added buttons on the sidebar to link to embargoes and leases
  app/views/hyrax/dashboard/_sidebar.html.erb
  config/locales/en.yml
Labels: approved, ready_to_merge

#417 Fixed the pop up message in the datatcite doi
  app/assets/javascripts/ubiquity/external_services_modal.js
  app/helpers/ubiquity/permission_badge_helper.rb
  app/views/hyrax/base/_form_progress.html.erb
Labels: approved, ready_to_merge

#418 removed debug and relevance score from search page
  app/views/shared/ubiquity/catalog/_index_list_default.html.erb
Labels: ready_to_merge

#420 Populate resource type for Exhibition item
  config/authorities/resource_types.yml
Labels: approved, ready_to_merge

#419 disabled action button in show work page if the user is not logged in
  app/views/shared/ubiquity/file_sets/_actions.html.erb
Labels: approved, ready_to_merge

#421 Added the support for the url in the orcid and the isni value
  app/helpers/multiple_metadata_fields_helper.rb
Labels: approved, ready_to_merge

#425 Add service_code to indexer posting
  app/services/ubiquity/indexer_client.rb
Labels: approved

#426 Add work type time based media
  app/views/records/edit_fields/_resource_type.html.erb
  config/authorities/resource_types.yml
Labels: approved, ready_to_merge

#424 fix shared-search to index multiple files from the same work
  app/models/concerns/ubiquity/update_shared_index.rb
  app/models/file_set.rb
  app/services/ubiquity/shared_index_solr_service_wrapper.rb
  lib/tasks/add_tenant_cname_to_work.rake
Labels: approved, ready_to_merge

#423 Featured work list issue
  app/views/hyrax/homepage/_featured.html.erb
Labels: approved, ready_to_merge

#427 reviewd logic to create fileavailability facet
  app/models/concerns/ubiquity/multiple_modules.rb
Labels: approved, ready_to_merge

#429 file-availability filter switched off
  app/controllers/catalog_controller.rb
  app/models/article.rb
  app/models/book.rb
  app/models/book_contribution.rb
  app/models/concerns/ubiquity/multiple_modules.rb
  app/models/conference_item.rb
  app/models/dataset.rb
  app/models/exhibition_item.rb
  app/models/generic_work.rb
  app/models/image.rb
  app/models/report.rb
  app/models/thesis_or_dissertation.rb
  app/models/time_based_media.rb
Labels: approved, ready_to_merge

#430 fixed a typo
  config/authorities/resource_types.yml
Labels: approved, ready_to_merge

#431 Fixed the issue in the keyword in RIF template
  app/controllers/concerns/ubiquity/citations_export_concern.rb
Labels: approved, ready_to_merge

#433 reverted changes to csv download, so the exported csv headers are no longer in same order as imported csv headers
  app/models/concerns/ubiquity/csv_export_util.rb
  app/services/ubiquity/csv_data.rb
  app/services/ubiquity/csv_data_remap.rb
  app/services/ubiquity/csv_generator.rb
Labels: approved

#434 Added the ENV variable for the s3 download switch specific to live url
  app/helpers/ubiquity/file_display_helpers.rb
Labels: approved, ready_to_merge

#432 revert ability of json importer to update records
  app/services/ubiquity/json_importer.rb
  app/services/ubiquity/queue_import.rb
Labels: approved, ready_to_merge

#436 Added code to modify the orcid and isni values
  app/models/concerns/ubiquity/all_models_virtual_fields.rb
Labels: approved, ready_to_merge
