Repository ubiquitypress/hyku, pull requests merged in 2019-08, with the labels that each got.

#499 Reduced text size to 18px
  app/views/admin/exports/index.html.erb
Labels: approved, ready_to_merge

#495 Fix to ensure that an unsed doi can now be assigned to a work
  app/controllers/ubiquity/external_services_controller.rb
  app/models/concerns/ubiquity/track_doi_options.rb
  app/models/external_service.rb
  app/services/ubiquity/doi_service.rb
  app/services/ubiquity/fetch_all_orcid_isni.rb
  app/views/hyrax/base/_guts4form.html.erb
  app/views/ubiquity/external_services/_datacite_suffix_generator.html.erb
Labels: approved, ready_to_merge

#500 Mailer report new changes
  app/indexers/shared_indexer.rb
  app/mailers/work_report_mailer.rb
  app/services/ubiquity/fetch_mailer_report_data.rb
  docker/supervisord-worker.conf
Labels: approved, ready_to_merge

#505 fix inability of super_admin administrator login from root_page or shared search page
  app/controllers/application_controller.rb
  app/controllers/ubiquity/superadmin_sessions_controller.rb
  app/views/_admin_util_links.html.erb
  app/views/shared/_footer.html.erb
  app/views/ubiquity/superadmin_sessions/_superadmin_login_link.html.erb
  app/views/ubiquity/superadmin_sessions/_superadmin_logout_link.html.erb
  app/views/ubiquity/superadmin_sessions/new.html.erb
  config/routes.rb
Labels: approved, ready_to_merge

#504 Fixed the blank value issue in OAI-PMH
  app/helpers/ubiquity/file_display_helpers.rb
  app/indexers/shared_indexer.rb
  app/models/solr_document.rb
  app/services/ubiquity/fetch_all_orcid_isni.rb
  app/views/hyrax/admin/stats/_email_reports.html.erb
Labels: approved, ready_to_merge

#503 Changed the help text according to the new specification
  app/views/admin/exports/index.html.erb
Labels: approved, ready_to_merge

#502 Added X in the regex to allow the value in generating the url for ORCID
  app/helpers/multiple_metadata_fields_helper.rb
  app/models/concerns/ubiquity/all_models_virtual_fields.rb
Labels: approved, ready_to_merge

#501 fixed the issue with blu icon for embargoed files and download link
  app/views/shared/ubiquity/file_sets/_actions.html.erb
  app/views/shared/ubiquity/file_sets/_restricted_media.html.erb
Labels: approved, ready_to_merge

#507 Oai pmh new changes
  app/indexers/shared_indexer.rb
  app/models/solr_document.rb
  app/services/ubiquity/fetch_tenant_url.rb
Labels: approved, ready_to_merge

#506 Fixed the issue with the label in creator/editor/contributor
  app/views/shared/ubiquity/contributor/_contributor_js.html.erb
  app/views/shared/ubiquity/contributor/_edit_array_hash_form.html.erb
  app/views/shared/ubiquity/contributor/_new_form.html.erb
  app/views/shared/ubiquity/creator/_creator_js.html.erb
  app/views/shared/ubiquity/creator/_edit_array_hash_form.html.erb
  app/views/shared/ubiquity/creator/_new_form.html.erb
  app/views/shared/ubiquity/editor/_edit_array_hash_form.html.erb
  app/views/shared/ubiquity/editor/_editor_js.html.erb
  app/views/shared/ubiquity/editor/_new_form.html.erb
Labels: approved, ready_to_merge

#508 allow multiple: true for duration field
  app/models/concerns/ubiquity/shared_metadata.rb
Labels: approved, ready_to_merge

#510 Addressed nil error on split when running rake task to resave a work
  app/models/concerns/ubiquity/track_doi_options.rb
Labels: approved, ready_to_merge

#509 further re-ordering of csv headers during export
  app/services/ubiquity/csv_data_remap.rb
  app/services/ubiquity/csv_generator.rb
Labels: approved, ready_to_merge

#511 add series_name back to csv_export
  app/services/ubiquity/csv_data_remap.rb
Labels: approved, ready_to_merge

#512 Oai request url fix
  app/controllers/application_controller.rb
  app/controllers/catalog_controller.rb
  app/controllers/ubiquity/oai_extension.rb
  app/models/current_scope.rb
  app/views/work_report_mailer/_table_data.html.erb
  config/application.rb
Labels: approved, ready_to_merge

#514 Removing the 3000 port in the tenant url address
  app/services/ubiquity/fetch_tenant_url.rb
Labels: approved, ready_to_merge

#515 revert changes that caused wrong ordering of json in csv column headers
  app/services/ubiquity/csv_generator.rb
Labels: approved, ready_to_merge

#516 Fixed the issue with the oai-pmh
  app/indexers/exhibition_item_indexer.rb
  app/indexers/thesis_or_dissertation_indexer.rb
  app/indexers/time_based_media_indexer.rb
  app/services/ubiquity/fetch_tenant_url.rb
Labels: approved, ready_to_merge

#517 add the alternative_journal_title field in the export
  app/services/ubiquity/csv_data_remap.rb
Labels: ready_to_merge

#518 Added publich filter for the oai
  app/controllers/ubiquity/solr_wrapper_extension.rb
  config/application.rb
Labels: approved, ready_to_merge

#519 Fixed the issue with the pending review
  app/controllers/ubiquity/solr_wrapper_extension.rb
Labels: approved, ready_to_merge

#520 Fixed the issue with the collection
  app/controllers/ubiquity/oai_extension.rb
  app/controllers/ubiquity/oai_solr_wrapper_extension.rb
  config/application.rb
Labels: approved, ready_to_merge

#522 Added the base url configurable for the s3
  app/services/ubiquity/importer_client.rb
Labels: approved, ready_to_merge

#521 Added soruce url link for the collection
  app/indexers/collection_indexer.rb
  app/models/solr_document.rb
  app/services/ubiquity/fetch_tenant_url.rb
Labels: approved, ready_to_merge

#525 refactoring mailer code
  app/mailers/work_report_mailer.rb
  app/services/ubiquity/fetch_mailer_report_data.rb
Labels: approved, ready_to_merge

#526 shared-search now uses db settings to determine tenants to exempt from shared-search
  app/controllers/ubiquity/account_settings_controller.rb
  app/models/concerns/ubiquity/account_self_join_association.rb
  app/models/concerns/ubiquity/update_shared_index.rb
  app/views/ubiquity/account_settings/edit.html.erb
  app/views/ubiquity/account_settings/index.html.erb
Labels: approved, ready_to_merge

#527 Revert "Merge pull request #525 from ubiquitypress/refactor-mailer"
  app/mailers/work_report_mailer.rb
  app/services/ubiquity/fetch_mailer_report_data.rb
Labels: approved

#523 Added new indexer for the mailer
  app/mailers/work_report_mailer.rb
  app/services/ubiquity/doi_service.rb
  app/services/ubiquity/report_mailer.rb
Labels: approved, ready_to_merge

#528 refactor emailer preview to use ENV variables
  docker-entrypoint.sh
  spec/mailers/previews/work_report_mailer_preview.rb
Labels: approved, ready_to_merge

#530 add pre-selected institution field choice for bl-dem and kew-demo
  app/helpers/ubiquity/preselect_institution_helper.rb
Labels: approved, ready_to_merge

#531 making a manual doi a clickable link
  app/models/concerns/ubiquity/track_doi_options.rb
  app/renderers/ubiquity/external_url_attribute_renderer.rb
Labels: approved, ready_to_merge

#533 fix modal behaviour that interfered with the compulsory field warning…
  app/assets/javascripts/ubiquity/external_services_modal.js
  app/views/ubiquity/external_services/_datacite_modal.html.erb
Labels: approved, ready_to_merge

#534 rescue tcp connection error when posting to indexer
  app/services/ubiquity/indexer_client.rb
Labels: approved, ready_to_merge

#532 add static ip to docker-compose files
  config/database.yml
  db/schema.rb
  docker/docker-compose.dev.yml
  docker/local-docker-compose.yml
Labels: approved, ready_to_merge

#535 fix issue with clear filters linking to the wrong page
  app/assets/javascripts/ubiquity/search_page.js
  docker/docker-compose.no-load-balance-dev.yml
Labels: approved, ready_to_merge

#536 refactor to address the error occured due to the official url and doi…
  app/renderers/ubiquity/external_url_attribute_renderer.rb
  app/views/hyrax/base/_attribute_rows.html.erb
Labels: approved, ready_to_merge

#529 in-place Edit for account settings
  app/controllers/ubiquity/account_settings_controller.rb
  app/views/ubiquity/account_settings/edit.html.erb
  app/views/ubiquity/account_settings/index.html.erb
  app/views/ubiquity/account_settings/settings/_contact_email.html.erb
  app/views/ubiquity/account_settings/settings/_monthly_email_list.html.erb
  app/views/ubiquity/account_settings/settings/_partial_for_text_field.html.erb
  app/views/ubiquity/account_settings/settings/_weekly_email_list.html.erb
  app/views/ubiquity/account_settings/settings/_yearly_email_list.html.erb
  app/views/ubiquity/account_settings/settings/contact_email.js.erb
  app/views/ubiquity/account_settings/settings/monthly_email_list.js.erb
  app/views/ubiquity/account_settings/settings/weekly_email_list.js.erb
  app/views/ubiquity/account_settings/settings/yearly_email_list.js.erb
  config/routes.rb
Labels: approved, ready_to_merge

#538 fixing regression issue causing a click to a work to redirect to the …
  app/assets/javascripts/ubiquity/search_page.js
Labels: approved, ready_to_merge

#537 Fix positiong issue with approval form
  app/assets/javascripts/application.js
  app/assets/javascripts/ubiquity/work_page.js
  app/views/hyrax/base/show.html.erb
Labels: approved, ready_to_merge

#540 refactor enable doi method to check for the tenant name presence in t…
  app/models/concerns/ubiquity/work_doi_lifecycle.rb
Labels: approved, ready_to_merge
