Repository ubiquitypress/hyku, pull requests merged in 2019-05, with the labels that each got.

#345 fix error to stop post-indexer job to be called twice
  app/models/concerns/ubiquity/track_doi_options.rb
  app/models/concerns/ubiquity/work_doi_lifecycle.rb
  app/services/ubiquity/indexer_client.rb
Labels: approved, ready_to_merge

#346 Added nil check condition for the tenant
  app/helpers/ubiquity/file_display_helpers.rb
Labels: approved, ready_to_merge

#347 Reverted the file_status column with boolean value
  app/controllers/concerns/ubiquity/uploads_controller_override.rb
  app/controllers/ubiquity/fail_uploads_controller.rb
  app/models/concerns/ubiquity/file_upload_callback.rb
Labels: approved, ready_to_merge

#344 S3 url integration
  app/helpers/ubiquity/file_display_helpers.rb
  app/services/ubiquity/importer_client.rb
Labels: approved, ready_to_merge

#348 S3 url fallback code condition
  app/helpers/ubiquity/file_display_helpers.rb
Labels: approved, ready_to_merge

#349 Publication year modal
  app/assets/javascripts/application.js
  app/assets/javascripts/ubiquity/external_services_modal.js
  app/assets/stylesheets/ubiquity.scss
  app/views/hyrax/base/_form_progress.html.erb
  app/views/ubiquity/external_services/_datacite_modal.html.erb
  app/views/ubiquity/external_services/_doi_options.html.erb
Labels: approved, ready_to_merge

#352 Change to doi help text in the deposit form
  config/locales/article.en.yml
  config/locales/book_contribution.en.yml
  config/locales/conference_item.en.yml
  config/locales/dataset.en.yml
  config/locales/report.en.yml
Labels: ready_to_merge

#354 Added routes to download the file from s3 without exposing the url
  app/controllers/ubiquity/fail_uploads_controller.rb
  app/helpers/ubiquity/file_display_helpers.rb
  config/routes.rb
Labels: approved, ready_to_merge

#355 fixed issue with field overlapping with datacite modal for external s…
  app/views/admin/groups/edit.html.erb
  app/views/hyrax/base/_form_progress.html.erb
  app/views/hyrax/base/new.html.erb
  app/views/ubiquity/external_services/_datacite_modal.html.erb
Labels: approved, ready_to_merge

#356 Universal viewer
  app/controllers/hyrax/articles_controller.rb
  app/controllers/hyrax/book_contributions_controller.rb
  app/controllers/hyrax/books_controller.rb
  app/controllers/hyrax/conference_items_controller.rb
  app/controllers/hyrax/datasets_controller.rb
  app/controllers/hyrax/generic_works_controller.rb
  app/controllers/hyrax/images_controller.rb
  app/controllers/hyrax/reports_controller.rb
  app/helpers/ubiquity/file_display_helpers.rb
  app/views/shared/ubiquity/_thumbnail_featured.html.erb
  app/views/shared/ubiquity/_thumbnail_icons_with_restrictions.html.erb
  app/views/shared/ubiquity/file_sets/_restricted_media.html.erb
  config/application.rb
Labels: approved, ready_to_merge

#357 modal for datacite rendering from form progress
  app/views/admin/groups/edit.html.erb
  app/views/hyrax/base/_form_progress.html.erb
  app/views/hyrax/base/new.html.erb
  app/views/ubiquity/external_services/_datacite_modal.html.erb
Labels: ready_to_merge

#359 fix to allow universal viewer to work on sandbox
  app/helpers/ubiquity/file_display_helpers.rb
  app/views/shared/ubiquity/_thumbnail_featured.html.erb
  app/views/shared/ubiquity/_thumbnail_icons_with_restrictions.html.erb
  app/views/shared/ubiquity/file_sets/_restricted_media.html.erb
Labels: ready_to_merge

#358 Pull metadata from crossref
  app/assets/javascripts/application.js
  app/assets/javascripts/ubiquity/datacite.js
  app/controllers/available_ubiquity_titles_controller.rb
  app/forms/ubiquity/all_forms_shared_behaviour.rb
  app/services/ubiquity/crossref_response.rb
  app/services/ubiquity/datacite_client.rb
  app/services/ubiquity/datacite_response.rb
  app/views/records/edit_fields/_eissn.html.erb
  app/views/records/edit_fields/_isbn.html.erb
  app/views/records/edit_fields/_issn.html.erb
  app/views/records/edit_fields/_journal_title.html.erb
  app/views/records/edit_fields/_keyword.html.erb
  app/views/records/edit_fields/_publisher.html.erb
  app/views/shared/ubiquity/_datacite_doi.html.erb
  app/views/shared/ubiquity/_datacite_js.html.erb
  app/views/shared/ubiquity/creator/_new_form.html.erb
  config/locales/hyrax.en.yml
Labels: approved, ready_to_merge

#361 allow to send updates to datacite
  app/models/concerns/ubiquity/work_doi_lifecycle.rb
Labels: approved, ready_to_merge

#360 Modal issue datacite
  app/assets/javascripts/ubiquity/external_services_modal.js
  app/views/hyrax/base/_form_progress.html.erb
  app/views/hyrax/base/edit.html.erb
  app/views/hyrax/base/new.html.erb
  app/views/ubiquity/external_services/_datacite_modal.html.erb
Labels: approved, ready_to_merge

#362 change announcement background color
  app/assets/stylesheets/ubiquity.scss
Labels: ready_to_merge

#364 New shared search
  app/helpers/application_helper.rb
  app/helpers/ubiquity/file_display_helpers.rb
  app/helpers/ubiquity/shared_search_helper.rb
  app/models/article.rb
  app/models/book.rb
  app/models/book_contribution.rb
  app/models/collection.rb
  app/models/concerns/ubiquity/account_self_join_association.rb
  app/models/concerns/ubiquity/update_shared_index.rb
  app/models/conference_item.rb
  app/models/dataset.rb
  app/models/generic_work.rb
  app/models/image.rb
  app/models/report.rb
  app/models/ubiquity.rb
  app/services/ubiquity/shared_index_solr_service_wrapper.rb
  app/views/catalog/_index_header_list_default.html.erb
  app/views/shared/ubiquity/file_sets/_restricted_media.html.erb
  app/views/shared/ubiquity/search_display/_search_thumbnail.html.erb
  app/views/splash/shared_layer.html.erb
  config/application.rb
  db/migrate/20190513100115_add_parent_id_and_data_settings_column_to_account.rb
  db/schema.rb
  lib/tasks/ubiquity_create_parent_account.rake
  lib/tasks/ubiquity_populate_account_parent_id.rake
  lib/tasks/ubiquity_reindex_shared_search.rake
Labels: approved, ready_to_merge

#363 Added License manipulation for crossreg and Datacite
  app/services/ubiquity/crossref_response.rb
  app/services/ubiquity/datacite_client.rb
  app/services/ubiquity/datacite_response.rb
Labels: approved, ready_to_merge

#366 Repetead retries
  app/services/ubiquity/indexer_client.rb
Labels: ready_to_merge

#365 Highlight fields based on ui
  app/assets/javascripts/ubiquity/datacite.js
  app/services/ubiquity/crossref_response.rb
  app/services/ubiquity/datacite_response.rb
Labels: approved, ready_to_merge

#367 fix issue of private icon file notdisplaying for logged out user on s…
  app/views/shared/ubiquity/search_display/_search_thumbnail.html.erb
Labels: ready_to_merge

#368 Change to the footer
  app/views/shared/_footer.html.erb
  config/locales/hyrax.en.yml
  public/bower_includes/universalviewer/dist/uv-2.0.1/lib/uv-seadragon-extension.en-GB.config.json
Labels: ready_to_merge

#369 address user case when user does not manually enter the doi in correc…
  app/models/concerns/ubiquity/track_doi_options.rb
Labels: approved, ready_to_merge

#371 new-shared-search frontend display tweaks
  app/controllers/catalog_controller.rb
  app/helpers/application_helper.rb
  app/helpers/ubiquity/facet_helper_behavior_override.rb
  app/views/_controls.html.erb
  app/views/catalog/_index_list_default.html.erb
  app/views/catalog/index.html.erb
Labels: approved, ready_to_merge

#372 Refresh order and text changes
  app/assets/javascripts/application.js
  app/assets/javascripts/ubiquity/custom_required_fields.js
  app/assets/javascripts/ubiquity/preselect_institution_by_tenant.js
  app/assets/stylesheets/application.css
  app/assets/stylesheets/work_type_modal.scss
  app/forms/hyrax/article_form.rb
  app/forms/hyrax/book_contribution_form.rb
  app/forms/hyrax/book_form.rb
  app/forms/hyrax/conference_item_form.rb
  app/forms/hyrax/dataset_form.rb
  app/forms/hyrax/generic_work_form.rb
  app/forms/hyrax/image_form.rb
  app/forms/hyrax/report_form.rb
  app/forms/ubiquity/all_forms_shared_behaviour.rb
  app/helpers/multiple_metadata_fields_helper.rb
  app/helpers/ubiquity/preselect_institution_helper.rb
  app/views/hyrax/base/_attribute_rows.html.erb
  app/views/hyrax/base/_form_metadata.html.erb
  app/views/hyrax/base/_guts4form.html.erb
  app/views/hyrax/base/_ubiquity_metadata.html.erb
  app/views/hyrax/base/_work_title.html.erb
  app/views/records/edit_fields/_institution.html.erb
  app/views/records/edit_fields/_publisher.html.erb
  app/views/records/edit_fields/_title.html.erb
  app/views/records/edit_fields/_version_number.html.erb
  app/views/records/edit_fields/_volume.html.erb
  app/views/shared/ubiquity/contributor/_edit_array_hash_form.html.erb
  app/views/shared/ubiquity/contributor/_new_form.html.erb
  app/views/shared/ubiquity/contributor/_show_array_hash.html.erb
  app/views/shared/ubiquity/creator/_edit_array_hash_form.html.erb
  app/views/shared/ubiquity/creator/_new_form.html.erb
  app/views/shared/ubiquity/creator/_show_array_hash.html.erb
  app/views/shared/ubiquity/editor/_edit_array_hash_form.html.erb
  app/views/shared/ubiquity/editor/_new_form.html.erb
  app/views/shared/ubiquity/editor/_show_array_hash.html.erb
  app/views/shared/ubiquity/event_date/_event_date.html.erb
  app/views/shared/ubiquity/related_identifier/_edit_array_hash_form.html.erb
  app/views/shared/ubiquity/related_identifier/_new_form.html.erb
  app/views/shared/ubiquity/related_identifier/_show_array_hash.html.erb
  app/views/shared/ubiquity/works/_custom_work_title.html.erb
  config/authorities/relation_type.yml
  config/locales/article.en.yml
  config/locales/book.en.yml
  config/locales/book_contribution.en.yml
  config/locales/conference_item.en.yml
  config/locales/dataset.en.yml
  config/locales/generic_work.en.yml
  config/locales/hyrax.en.yml
  config/locales/report.en.yml
Labels: approved, ready_to_merge

#374 Fix draft-doi display flow
  app/helpers/ubiquity/external_services_helper.rb
  app/views/hyrax/base/_form_progress.html.erb
Labels: ready_to_merge

#375 Added required tag for the resource type
  app/views/records/edit_fields/_resource_type.html.erb
Labels: approved, ready_to_merge

#376 add solr relevance score and work creation to date to frontend of new-shared-search display
  app/views/catalog/_index_header_list_default.html.erb
  app/views/catalog/_index_list_default.html.erb
  app/views/shared/ubiquity/catalog/_index_header_list_default.html.erb
  app/views/shared/ubiquity/catalog/_index_list_default.html.erb
Labels: approved, ready_to_merge

#377 Added book title and the collection in the display form
  app/forms/hyrax/generic_work_form.rb
  app/views/hyrax/base/_attribute_rows.html.erb
  app/views/shared/ubiquity/collections/_show_collection_list.html.erb
Labels: approved, ready_to_merge

#378 Alternate title
  app/assets/javascripts/application.js
  app/assets/javascripts/ubiquity/custom_required_fields.js
  app/assets/javascripts/ubiquity/title_check.js
  app/controllers/available_ubiquity_titles_controller.rb
  app/controllers/catalog_controller.rb
  app/forms/hyrax/article_form.rb
  app/forms/hyrax/book_contribution_form.rb
  app/forms/hyrax/book_form.rb
  app/forms/hyrax/conference_item_form.rb
  app/forms/hyrax/dataset_form.rb
  app/forms/hyrax/generic_work_form.rb
  app/forms/hyrax/image_form.rb
  app/forms/hyrax/report_form.rb
  app/forms/ubiquity/all_forms_shared_behaviour.rb
  app/models/concerns/ubiquity/basic_metadata_decorator.rb
  app/models/concerns/ubiquity/shared_metadata.rb
  app/models/solr_document.rb
  app/presenters/hyku/manifest_enabled_work_show_presenter.rb
  app/services/ubiquity/title_checker.rb
  app/views/hyrax/base/_attribute_rows.html.erb
  app/views/records/edit_fields/_alternative_journal_title.html.erb
  app/views/records/edit_fields/_alternative_title.html.erb
  app/views/records/edit_fields/_resource_type.html.erb
  app/views/records/edit_fields/_title.html.erb
  config/locales/article.en.yml
Labels: approved

#379 made Journal Title as required field for Article
  app/assets/javascripts/ubiquity/custom_required_fields.js
Labels: approved, ready_to_merge

#380 Validation message
  app/assets/javascripts/ubiquity/external_services_modal.js
  app/helpers/application_helper.rb
  app/helpers/ubiquity/work_show_actions_helper.rb
  app/views/hyrax/base/_show_actions.html.erb
  app/views/records/edit_fields/_official_link.html.erb
  app/views/shared/ubiquity/works/_show_actions.html.erb
Labels: approved, ready_to_merge

#382 Fix embargo not expiring
  app/services/ubiquity/expiry_service.rb
Labels: approved, ready_to_merge
