Repository ubiquitypress/hyku, pull requests merged in 2019-11, with the labels that each got.

#600 allow contact form to be submitted via api call
  app/controllers/api/v1/contact_form_controller.rb
  app/mailers/hyrax/contact_mailer.rb
  config/application.rb
  config/routes.rb
  spec/controllers/api/v1/contact_form_controller_spec.rb
Labels: approved, ready_to_merge

#601 files and collection only available at single work endpoint
  app/controllers/api/v1/work_controller.rb
  app/services/ubiquity/api_utils.rb
  app/views/api/v1/work/_work.json.jbuilder
Labels: approved, ready_to_merge

#602 dont display works that are under review in search
  app/controllers/api/v1/search_controller.rb
Labels: approved, ready_to_merge

#603 adding google tag manager key to tenant end point
  app/views/api/v1/tenant/_tenant.json.jbuilder
Labels: approved, ready_to_merge

#605 add a filter to solr filter query in search-controller
  app/controllers/api/v1/search_controller.rb
Labels: ready_to_merge

#606 add ability to sort or filter by relevance, date_published and date_published descending
  app/controllers/api/v1/search_controller.rb
  app/controllers/concerns/ubiquity/api_controller_utility_methods.rb
Labels: approved, ready_to_merge

#607 Ordering featured work
  app/controllers/api/v1/highlights_controller.rb
  app/controllers/concerns/ubiquity/api_controller_utility_methods.rb
Labels: ready_to_merge

#609 adding featured_order to highlights endpoint to allow reordering of f…
  app/controllers/api/v1/highlights_controller.rb
  app/views/api/v1/highlights/index.json.jbuilder
  docker/docker-compose.yml
Labels: approved, ready_to_merge

#611 ensure the whole data obj is returned to retrieve the featured works
  app/controllers/api/v1/highlights_controller.rb
Labels: approved, ready_to_merge

#610 using Hyrax::DerivativePath.derivative_path_for_reference to get thumbnail path
  app/controllers/api/v1/work_controller.rb
  app/services/ubiquity/api_utils.rb
Labels: approved, ready_to_merge

#615 error handling for collections
  app/services/ubiquity/api_utils.rb
Labels: ready_to_merge

#619 passing the featured order to highlights end-point
  app/views/api/v1/highlights/index.json.jbuilder
Labels: approved

#621 add caching to /work/id and /collection/id single endpoint
  app/controllers/api/v1/collection_controller.rb
  app/controllers/api/v1/highlights_controller.rb
  app/controllers/api/v1/work_controller.rb
  app/models/concerns/ubiquity/caching_single.rb
  app/services/ubiquity/api_utils.rb
  app/views/api/v1/collection/_collection.json.jbuilder
  app/views/api/v1/collection/show.json.jbuilder
  app/views/api/v1/highlights/index.json.jbuilder
  app/views/api/v1/work/show.json.jbuilder
  config/application.rb
Labels: approved

#625 added more caching
  app/controllers/api/v1/collection_controller.rb
  app/controllers/api/v1/work_controller.rb
  app/models/concerns/ubiquity/caching_single.rb
  app/services/ubiquity/api_utils.rb
  app/views/api/v1/collection/_collection.json.jbuilder
  app/views/api/v1/collection/_work.json.jbuilder
  app/views/api/v1/work/_work.json.jbuilder
Labels: approved

#629 fixed the regression issue that returned the wrong json for manifest …
  app/controllers/api/v1/work_controller.rb
Labels: approved

#628 cache facet endpoint and add an additional endpoint api/search/facet/…
  app/controllers/api/v1/search_controller.rb
Labels: approved, ready_to_merge

#630 use a more robust naming scheme for facet cache key
  app/controllers/api/v1/search_controller.rb
Labels: approved

#633 update the routes for citations to serve the new front end
  config/routes.rb
Labels: ready_to_merge

#634 re-included module for error handling in the search controller
  app/controllers/api/v1/search_controller.rb
Labels: approved, ready_to_merge

#635 fix cache expiration for single record
  app/models/article.rb
  app/models/book.rb
  app/models/book_contribution.rb
  app/models/collection.rb
  app/models/concerns/ubiquity/caching_single.rb
  app/models/conference_item.rb
  app/models/dataset.rb
  app/models/exhibition_item.rb
  app/models/generic_work.rb
  app/models/image.rb
  app/models/report.rb
  app/models/thesis_or_dissertation.rb
  app/models/time_based_media.rb
  config/application.rb
Labels: approved, ready_to_merge

#637 Shared layer blank
  app/views/_controls.html.erb
  app/views/_logo.html.erb
  app/views/_masthead.html.erb
  app/views/hyrax/homepage/_announcement.html.erb
  app/views/hyrax/homepage/_marketing.html.erb
  app/views/hyrax/homepage/index.html.erb
  app/views/layouts/hyrax.html.erb
  app/views/splash/shared_layer.html.erb
Labels: ready_to_merge
