Repository ubiquitypress/hyku, pull requests merged in 2019-10, with the labels that each got.

#573 add type attribute to work and collection objects. Also use system_modified_dtsi from to_solr instead of date_modified for collection object
  app/controllers/api/v1/collection_controller.rb
  app/controllers/api/v1/highlights_controller.rb
  app/controllers/api/v1/work_controller.rb
  app/views/api/v1/collection/_collection.json.jbuilder
  app/views/api/v1/files/index.json.jbuilder
  app/views/api/v1/work/_work_only.json.jbuilder
Labels: approved, ready_to_merge

#574 add thumbnail_url for work and collection. Ensure tenant endpoint does not return root account that is account where parent_id is nil. use custom request.env[HTTP_HOST] so universal viewer can work
  app/controllers/api/v1/collection_controller.rb
  app/controllers/api/v1/files_controller.rb
  app/controllers/api/v1/highlights_controller.rb
  app/controllers/api/v1/tenant_controller.rb
  app/controllers/api/v1/work_controller.rb
  app/views/api/v1/collection/_collection.json.jbuilder
  app/views/api/v1/work/_work_only.json.jbuilder
Labels: approved, ready_to_merge

#577 add low level caching using Rails.cache to /work endpoint
  Gemfile
  Gemfile.lock
  app/controllers/api/v1/work_controller.rb
  app/views/api/v1/collection/index.json.jbuilder
  app/views/api/v1/work/index.json.jbuilder
  config/initializers/ubiquity_cache_store.rb
Labels: approved, ready_to_merge

#579 add tenant endpoint with site and content block information
  app/controllers/api/v1/tenant_controller.rb
  app/models/concerns/ubiquity/account_self_join_association.rb
  app/views/api/v1/tenant/_tenant.json.jbuilder
  app/views/api/v1/tenant/index.json.jbuilder
  app/views/api/v1/tenant/show.json.jbuilder
Labels: approved

#581 add type field to work end point
  app/views/api/v1/work/_work.json.jbuilder
Labels: approved, ready_to_merge

#582 fixed alternative title and resource type field on the work endpoint …
  app/views/api/v1/work/_work.json.jbuilder
Labels: approved, ready_to_merge

#583 add fix to prevent posting to api importer if cname is localhost
  app/models/file_set.rb
Labels: approved, ready_to_merge

#584 Upload files from fedora to solr
  app/services/ubiquity/load_fedora_to_solr.rb
  app/services/ubiquity/load_fedora_uri_files.rb
  lib/uri_json/missing-repo-index_bl-demo.json
  lib/uri_json/missing-repo-index_bl.json
  lib/uri_json/missing-repo-index_britishmuseum-demo.json
  lib/uri_json/missing-repo-index_kew.json
  lib/uri_json/missing-repo-index_mola.json
  lib/uri_json/missing-repo-index_nms-demo.json
  lib/uri_json/missing-repo-index_nms.json
  lib/uri_json/missing-repo-index_tate-demo.json
  lib/uri_json/missing-repo-index_tate.json
Labels: approved, ready_to_merge

#585 Add missing field from work endpoint
  app/views/api/v1/work/_work.json.jbuilder
Labels: approved, ready_to_merge

#588 add missed nms indexes
  lib/uri_json/missed-indexes-nms.json
Labels: approved, ready_to_merge

#589 add search to the rest api
  app/assets/javascripts/api/v1/search.coffee
  app/assets/stylesheets/api/v1/search.scss
  app/controllers/api/v1/search_controller.rb
  app/helpers/api/v1/search_helper.rb
  app/views/api/v1/search/index.json.jbuilder
  config/routes.rb
  spec/controllers/api/v1/search_controller_spec.rb
  spec/helpers/api/v1/search_helper_spec.rb
Labels: approved, ready_to_merge

#586 revert to using redis as cache store
  app/controllers/api/v1/collection_controller.rb
  app/controllers/api/v1/highlights_controller.rb
  app/controllers/api/v1/tenant_controller.rb
  app/controllers/api/v1/work_controller.rb
  app/controllers/concerns/ubiquity/api_controller_utility_methods.rb
  config/environments/production.rb
  config/initializers/redis.rb
  config/initializers/ubiquity_cache_store.rb
  config/redis_cache.yml
  docker/local-docker-compose.yml
Labels: approved, ready_to_merge, review_needed

#587 add file licences to files endpoint
  app/views/api/v1/files/index.json.jbuilder
Labels: approved, ready_to_merge

#590 refactor manifest error to assign the host to account_cname
  app/controllers/api/v1/work_controller.rb
Labels: approved

#592 api /highlights endpoints will store individual query result in redis and then store highlights index.json.jbuilder rendered content in redis too
  app/controllers/api/v1/highlights_controller.rb
  app/views/api/v1/highlights/index.json.jbuilder
Labels: approved, ready_to_merge

#593 add list of query fields using qf key to solr query
  app/controllers/api/v1/search_controller.rb
  app/controllers/concerns/ubiquity/api_controller_utility_methods.rb
Labels: approved, ready_to_merge

#594 change the query for the tenant end point now using name instead of c…
  app/controllers/api/v1/tenant_controller.rb
Labels: approved, ready_to_merge

#596 -search api no longer returns private work types; - filtering by a query term that does not exist and a facet filter will return zero record, - search api query no longer returns file_sets, - total number of results will be correct when adding/removing filter
  app/controllers/api/v1/search_controller.rb
  app/helpers/ubiquity/file_display_helpers.rb
  app/views/api/v1/collection/_collection.json.jbuilder
Labels: approved, ready_to_merge

#595 add information about embargo and lease dates on file end-point
  app/views/api/v1/files/index.json.jbuilder
Labels: approved, ready_to_merge

#598 ensure highlights endoint uses the correct timestamp for cache. Also added a new facet endpoint to api search
  app/controllers/api/v1/highlights_controller.rb
  app/controllers/api/v1/search_controller.rb
  config/routes.rb
Labels: approved, ready_to_merge

#599 add api endpoint that allows a work to be featured by calling /api/v1/tenant/:tenant_id/work/:work_id/featured_works
  app/assets/javascripts/api/v1/featured_works.coffee
  app/assets/stylesheets/api/v1/featured_works.scss
  app/controllers/api/v1/featured_works_controller.rb
  app/helpers/api/v1/featured_works_helper.rb
  config/routes.rb
  spec/controllers/api/v1/featured_works_controller_spec.rb
  spec/helpers/api/v1/featured_works_helper_spec.rb
Labels: approved, ready_to_merge
